#!/bin/sh
# ===========================================
# Redis Session Configuration Fix
# ===========================================
# Nextcloud image'ın REDIS_HOST_PASSWORD'ü session.save_path'e
# düzgün aktarmama sorunu için fix.

set -e

if [ -n "$REDIS_HOST_PASSWORD" ]; then
    echo "Configuring Redis session with password..."
    
    # Create PHP config with correct Redis session path
    cat > /usr/local/etc/php/conf.d/zzz-redis-session-fix.ini <<EOF
; Redis session handler fix - generated by before-starting hook
session.save_handler = redis
session.save_path = "tcp://${REDIS_HOST:-redis}:${REDIS_HOST_PORT:-6379}?auth=${REDIS_HOST_PASSWORD}"
redis.session.locking_enabled = 1
redis.session.lock_retries = -1
redis.session.lock_wait_time = 10000
EOF
    
    echo "Redis session configuration completed."
else
    echo "REDIS_HOST_PASSWORD not set, skipping Redis session fix."
fi
